services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: ra_centre_db2
    ports:
      - "3306:3306"  # Map container port to host port
    volumes:
      - mysql_data:/var/lib/mysql  # Persist data
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data:  # Named volume for data persistence
    driver: local