services:
  postgresql:
    image: postgres:13
    container_name: ra-centre_postgresql-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ra_centre
    ports:
      - "5432:5432"
    volumes:
      - postressql_data:/var/lib/postgresql/data

volumes:
  postressql_data: