# docker-compose.yml
version: "3.9"  # Specify the docker-compose version

services:
  web:
    build: .  # Build the image using the Dockerfile in the current directory
    ports:
      - "8082:8082"   
    secrets:
      - DB_PSWD
      - SSH_KEY
    volumes:
      - ./:/app
    env_file:
      - .env  # Specify the .env file
secrets:
  DB_PSWD:
    file: ./secrets/DB_PSWD.txt
  SSH_KEY:
    file: ./secrets/SSH_KEY.pem