name: web_scraper project Linting Checks

on:
  pull_request:
    paths:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Web Scraper dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r web_scraper/requirements.txt # Install from web_scraper
      - name: Analysing the Web Scraper code with pylint
        run: |
          pylint $(git ls-files 'web_scraper/*.py') # Lint only web_scraper files